title: Saratoga Road
description: >
  **I am Strata**, a super simple
  responsive site template freebie
  crafted by [HTML5 UP](http://html5up.net).
copyright: 2017
sass:
  sass_dir: assets/sass
url: saratogaroad.github.io
disqus_shortname: 
facebook_username:
twitter_username: #saratogaroad
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
