title: Saratoga Road
description: >
  **A random walk**
  tech, strategy, investing,
  sports, and life.
copyright: 2017
sass:
  sass_dir: assets/sass
url: saratogaroad.github.io
disqus_shortname: 
facebook_username:
twitter_username: "saratogaroad"
linkedin_username: 
instagram_username:
pinterest_username:
flickr_username:
github_username:  
feed_icon: rss
email: 
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
